### ISSUE TITLE
feat: client migrate to `pnpm` 

### ISSUE THREAD

**Issue by priyankarpal** [JasonDsouza212/moviebook#2]
currently we are using `npm` it's slow but `pnpm` Fast, disk space efficient package manager

https://pnpm.io/

I want to work on this issue

**Comment by piyushjha0409** [comment]
@priyankarpal have you raised the pr already on this?

**Comment by priyankarpal** [comment]
> @priyankarpal have you raised the pr already on this?

I haven't raised a PR but I created a branch. If I get assigned I will create the PR

**Comment by JasonDsouza212** [comment]
> currently we are using `npm` it's slow but `pnpm` Fast, disk space efficient package manager
> 
> https://pnpm.io/
> 
> I want to work on this issue

Yes that makes a lot of sense
